namespace VerifyTests;

public static class VerifyQuestPdf
{
    static readonly DateTimeOffset deterministicDate = new(2000, 1, 1, 0, 0, 0, TimeSpan.Zero);

    public static bool Initialized { get; private set; }

    public static void Initialize()
    {
        if (Initialized)
        {
            throw new("Already Initialized");
        }

        Initialized = true;

        InnerVerifier.ThrowIfVerifyHasBeenRun();
        VerifierSettings
            .AddExtraSettings(
                _ =>
                {
                    _.Converters.Add(new DocumentMetadataConverter());
                    _.Converters.Add(new DocumentSettingsConverter());
                });
        VerifierSettings.RegisterFileConverter<IDocument>(
            conversion: (document, settings) =>
            {
                // Names the page files, and says whether the verification wants the page images
                // and which pages it wants them for.
                var conversion = new PagedConversion(settings);

                // Rasterizing pages is expensive, so only do it when the page images are verified.
                // Otherwise the page count comes from the much cheaper vector svg generation.
                List<byte[]> pages = [];
                int pageCount;
                if (conversion.IncludeImages)
                {
                    pages = document.GenerateImages().ToList();
                    pageCount = pages.Count;
                }
                else
                {
                    pageCount = document.GenerateSvg().Count;
                }

                // QuestPDF stamps DateTimeOffset.Now into the PDF CreationDate/ModifiedDate on
                // every generation. Pin them to a fixed value so the info snapshot is stable; the
                // generated bytes are additionally run through PdfNormalizer below.
                var metadata = document.GetMetadata();
                metadata.CreationDate = deterministicDate;
                metadata.ModifiedDate = deterministicDate;
                conversion.Info = new
                {
                    Metadata = NullIfEmpty(metadata),
                    Settings = document.GetSettings(),
                };

                // Generating the pdf is expensive, so skip it entirely when the pdf target is excluded.
                // The rendered pages and info are unaffected. The pdf snapshot is always the full
                // document, regardless of PagesToInclude: PagesToInclude only trims the png pages below.
                if (!settings.IsTargetExcluded("pdf"))
                {
                    // Neutralize the volatile fields so the snapshot does not depend on anything the
                    // generator stamps in. The metadata dates above are already pinned, so today this
                    // only zeroes those; it also covers the trailer /ID and any XMP packet should a
                    // future QuestPDF or Skia version start emitting them.
                    var pdf = document.GeneratePdf();
                    if (settings.Normalize())
                    {
                        pdf = PdfNormalizer.Normalize(pdf);
                    }

                    // The source of the conversion: compared before the pages, which skip their
                    // comparers when it differs, and never converted again.
                    conversion.Source(new("pdf", new MemoryStream(pdf)));
                }

                // QuestPDF draws every page in one pass, so the pages PagesToInclude leaves out
                // were drawn as well. AddImages drops those, and the rest keep their page numbers.
                conversion.PageCount = pageCount;
                conversion.AddImages(pages);

                return conversion.Build();
            });
    }

    // Returns null when no displayed metadata members are set, so the empty `Metadata: {}` is omitted from the snapshot.
    static DocumentMetadata? NullIfEmpty(DocumentMetadata metadata)
    {
        if (metadata.Title == null &&
            metadata.Author == null &&
            metadata.Subject == null &&
            metadata.Keywords == null &&
            metadata.Creator == null &&
            metadata.Producer == null)
        {
            return null;
        }

        return metadata;
    }
}
